services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379 # Подключение к Redis-контейнеру

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
